### PR TITLE
Use voiceAssistant components

### PR DESCRIPTION
**Pull request by lukasIO**

### CODE REVIEW

**Comment by davidzhao** [comment]
@lukasIO trying this branch, I'm seeing a couple of things:
1. the colors aren't matching the theme, making it look a bit jarring
2. the bars aren't animating correctly when the agent is speaking, it's just showing full volume the entire time (as shown in screenshot)
3. there are a few style things, tagging @mattherzog to align on 
  - the glow around bars are gone
  - the bars are looking too tall

Before:

Screenshot 2024-09-11 at 8 46 14 AM

After:

Screenshot 2024-09-11 at 8 44 31 AM

**Comment by lukasIO** [comment]
thanks for taking a look! 
There's a bug in the currently used components version that prevented tailwind classes to be passed to the new visualizer. So I couldn't properly update the styling. 
Will update components and address the issues you mentioned.

**Comment by davidzhao** [comment]
> thanks for taking a look! There's a bug in the currently used components version that prevented tailwind classes to be passed to the new visualizer. So I couldn't properly update the styling. Will update components and address the issues you mentioned.

Ah ha.. CSS strikes again.

Thanks for updating everything.. code is much cleaner.

**Comment by lukasIO** [comment]
should be fixed now!

**Review by davidzhao — APPROVED** [review]
nice! :shipit:  🚀

**Pull request merged**
